from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^administrar/$', views.administrar, name='administrar'),
    url(r'^cliente/$', views.cliente, name='cliente'),
    url(r'^clientem/$', views.clientem, name='clientem'),
    url(r'^empleado/$', views.empleado, name='empleado'),
    url(r'^frozen/$', views.frozen, name='frozen'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^crud/agregar/$', views.crud_agregar, name='crud_agregar'),
    url(r'^crud/modificar/$', views.crud_mod, name='crud_mod'),
    url(r'^crud/eliminar/$', views.crud_eliminar, name='crud_eliminar'),
    url(r'^crud/congelar/$', views.crud_congelar, name='crud_congelar'),
    url(r'^carga/$', views.carga_mas, name='carga_mas'),
    url(r'^reporte/1/$', views.reporte1, name='reporte1'),
    url(r'^reporte/2/$', views.reporte2, name='reporte2'),
    url(r'^reporte/3/$', views.reporte3, name='reporte3'),
    url(r'^reporte/4/$', views.reporte4, name='reporte4'),
    url(r'^reporte/5/$', views.reporte5, name='reporte5'),
    url(r'^reporte/6/$', views.reporte6, name='reporte6'),
    url(r'^reporte/7/$', views.reporte7, name='reporte7'),
    url(r'^reporte/8/$', views.reporte8, name='reporte8'),
    url(r'^reporte/9/$', views.reporte9, name='reporte9'),
    url(r'^reporte/10/$', views.reporte10, name='reporte10'),
    url(r'^reporte/11/$', views.reporte11, name='reporte11'),
    url(r'^reporte/12/$', views.reporte12, name='reporte12'),
    url(r'^reporte/13/$', views.reporte13, name='reporte13'),
    url(r'^reporte/14/$', views.reporte14, name='reporte14'),
    url(r'^reporte/15/$', views.reporte15, name='reporte15'),
    url(r'^reporte/16/$', views.reporte16, name='reporte16'),
    url(r'^reporte/17/$', views.reporte17, name='reporte17'),
    url(r'^administrar/reporte/1/$', views.areporte1, name='areporte1'),
    url(r'^administrar/reporte/2/$', views.areporte2, name='areporte2'),
    url(r'^administrar/reporte/3/$', views.areporte3, name='areporte3'),
    url(r'^administrar/reporte/4/$', views.areporte4, name='areporte4'),
    url(r'^administrar/reporte/5/$', views.areporte5, name='areporte5'),
    url(r'^administrar/reporte/6/$', views.areporte6, name='areporte6'),
    url(r'^administrar/reporte/7/$', views.areporte7, name='areporte7'),
    url(r'^administrar/reporte/8/$', views.areporte8, name='areporte8'),
    url(r'^administrar/reporte/9/$', views.areporte9, name='areporte9'),
    url(r'^administrar/reporte/10/$', views.areporte10, name='areporte10'),
    url(r'^cliente/success/$', views.success, name='success'),


]
